# 예외 처리
## 기본개념과 예외처리 클래스

- 예외
    - 프로그램 내에서 발생하는 예외상황으로 프로그램 내에서 처리가 가능한 것
    - 배열의 크기에서 벗어난 인덱스에 접근하거나, 없는 파일을 열 때 등에서 발생
- 에러
    - JVM 내에서 발생하는 에러로 프로그램 내에서 처리가 불가능
    - ThreadDeath나 가상머신 오작동 등을 말함
- 확인된 예외
    - 잘못된 코드가 아닌 잘못된 상황에서 발생하는 예외
    - 파일 열기와 같이 정확한 코드로 구현했음에도, 외부 환경(파일이 없는 상황 등)에 따라 발생 가능
    - 예외처리를 구현하지 않으면 컴파일 에러 발생함(컴파일 시 확인된 예외)
    - RuntimeException 이외의 예외들
- 미확인 예외
    - 런타임 시 잘못 구현된 코드로 인해 발생하는 예외
    - 컴파일 에러가 나지 않지만 적절한 예외처리가 없을 경우 > 프로그램이 강제 종료
    - 컴파일 시 확인하지 않기 때문에 미확인 예외임
    - RuntimeException에 포함된 예외들

## try-catch-finally문

- try-catch-finally
    - 예외처리를 위한 가장 기본적인 문법
    - try : 실제 내용을 실행
    - catch : 예외 시 어떻게 처리할 것인지 결정
    - finally : 실제 내용에서 마무리해야할 내용이 있다면 마지막에 처리
- try-catch 구문
    - try에 수행할 코드를 작성한 후, catch 부분에서 예외처리를 해줌
    - catch()의 괄호 안에는 JVM에서 예외처리 시 생성하는 예외처리 객체를 담아줄 예외처리 클래스의 타이과 변수를 지정해줌
    - 메서드의 매개변수와 같은 개념
    - JVM에서 생성한 예외처리 객체와 catch 매개변수의 타입이 다를 경우 예외처리를 할 수 없어 프로그램이 종료
    - 따라서 catch 구문은 여러 개를 사용할 수 있고 발생 가능한 모든 예외에 대해 처리해줄 수 있어야 함
    - 그냥 예외 발생 시 예외 처리만 하면 되는 것을 굳이 이렇게 복잡하게 만들어둔 이유는 예외 발생 종류에 따라 다른 catch문의 내용을 실행하도록 하기 위함
    - 어떤 예외가 발생하던지 같은 로직으로 처리하고 싶다면 매개변수 타입을 가장 상위의 상속 클래스인 Exception타입으로 지정해주면 됨
    - 단 Exception 타입을 사용할 경우에는 가장 마지막에 위치해야함
- try-catch-finally 구문
    - try 구문을 수행하다 예외가 발생해서 catch문에서 예외 처리 후 종료된 경우, 예외 발생에 관계없이 try문과 한 쌍으로 수행될 수 있도록 해주는 것이 finally문
    - 굳이 finally를 사용하지 않고 아랫쪽에 코드를 작성해도 무방하지만 가독성을 위해 한 쌍으로 작성할 수 있도록 해줌
    - try에서 열어둔 자원(파일 등)을 해제해주는 코드를 넣을 때 많이 사용
    - 주의할 점은 try-catch-finally문은 각각 중괄호로 묶여 있기 때문에 서로 다른 스택 프레임을 가지게 됨
    - 즉 지역변수의 공유X
    - 따라서 서로 변수 공유를 하기 위해서는 구문 바깥쪽에 변수를 생성해줘야함
    - 그리고 파일 클래스와 같이 “확인된 예외”처리가 필수인 경우, finally 구문 안에서도 try-catch문을 통해 예외처리를 해줘야 컴파일 에러가 나지 않음

## try-with-resources문

- try-catch-finally구문을 사용할 때는 각각의 스택 프레임이 따로 생성되어 지역변수가 공유되지 않음
- try에서 열어둔 파일을 finally에서 닫기 위해서는 서로 파일의 참조변수를 공유해야하는데 변수 공유가 불가하니 구문 바깥쪽에서 변수를 생성하는 방식으로 해결할 수 밖에 없었음
- 그러다 보니 가독성도 떨어지고 자원을 일일이 해제해줘야 하는 번거로움이 생겨났는데, 이를 편하게 바꿔준 구문이 바로 try-with-resources
- try문의 생성자로 자원의 참조변수를 생성해주면 구문이 끝날 때 해당 참조변수의 자원을 자동으로 해제해줌
- try(참조변수=new객체생성){}catch(){}
- try() 괄호 안에 들어간 참조변수의 리소스는 구문이 끝날 때 자동으로 해제해줌

```java
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
public class Main{
  public static void main(String[] args){
    try{
    
    FileInputStream fi = new FileInputStream("a.txt");
    FileInputStream fi2 = new FileInputStream("a.txt");
    System.out.println(fi);//무언가 파일을 처리함
    int[]arr = {1,2,3,4,5};
    System.out.println(arr[5]);//예외발생지점
    
    } catch(IndexOutOfBoudsException i) {
    
      System.out.println("Invalid input");
      
    }catch(FileNotFoundException f}{
    
      System.out.println("Can't Open File");
    
    }catch(IOException io){
    
      System.out.println("Failed to close file");
    
    }
  }
}
```

## throws문

- 예외를 직접 처리하지 않고 던지는 것
- JVM에서 생성된 예외객체를 직접 처리하지 않고 그 메서드를 호출한 곳으로 넘겨줌(리턴과 ㅣ슷)
예외 객체가 반환되면 메서드를 호출한 곳에서는 그 예외 객체를 처리(catch)해줘야 함
- 메서드의 리턴값과 같이 throws가 선언된 생성자나 메서드는 실행 중 발생한 예외 객체를 직접 처리(catch)하지 않고 호출한 곳에 반환해 줌
- 메서드의 리턴값은 그냥 무시해도 되지만 예외 객체는 무시할 수가 없는 것이라 호출한 쪽에서 꼭 처리를 해줘야함

## 사용자 정의 예외 객체(throw)

- 기본 라이브러리(API)에서 제공하는 예외 객체 외 개발자가 선언해서 사용하는 예외 객체
- Exception클래스 또는 Exception의 자식 클래스를 반드시 상속받아야함
- 일반적으로 Exception에서 선언된 형태의 생성자 외에는 다른 멤버를 가지지 않은ㅁ
- 즉 Exception을 상속받는 예외 객체를 직접 만들고, 조건문을 사용해서 특정 상황에서 예외를 강제로 발생하도록 만들어줌
- 사실 이 경우 조건문이기 때문에 굳이 예외 객체를 생성하지 않더라도 처리하고 싶은 예외 상황을 조건문으로 처리하거나 예외 객체 대신 그냥 메서드로 생성해서  사용할 수도 있음
- 다만 명시적인 예외 객체를 사용함으로써 코드의 가시성을 높일 수 있ㄷ음
